FROM golang:1.25 as builder

WORKDIR /workspace
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o custom-deployment-controller main.go


FROM gcr.io/distroless/static:nonroot
WORKDIR /app
COPY --from=builder /workspace/custom-deployment-controller .
USER nonroot:nonroot
ENTRYPOINT ["custom-deployment-controller"]